### PR TITLE
Remove BUG() from kt_mutexset_unlock && add bad mutex unlock test

### LINKED ISSUE #105: kernel BUG at mm/ktsan/mutexset.c:32
The reason is probably that the kernel is trying to unlock a mutex in a different thread (which might be a false positive), but we do `kt_mutexset_unlock` before checking the thread id. And it BUGs when can't find the mutex being unlocked.

```
[  151.679331] kernel BUG at mm/ktsan/mutexset.c:32!
[  151.679331] invalid opcode: 0000 [#1] SMP 
[  151.679331] Modules linked in:
[  151.679331] CPU: 1 PID: 1192 Comm: ps Not tainted 4.2.0-ktsan #9
[  151.679331] Hardware name: Red Hat KVM, BIOS 0.5.1 01/01/2007
[  151.679331] task: ffff8800d8878480 ti: ffff88016cbfc000 task.ti: ffff88016cbfc000
[  151.679331] RIP: 0010:[<ffffffff81250ab3>]  [<ffffffff81250ab3>] kt_mutex_unlock+0x113/0x120
[  151.679331] RSP: 0018:ffff88016cbffa88  EFLAGS: 00010046
[  151.679331] RAX: 00000000ffffffff RBX: ffff8801a90ebd78 RCX: 0000000000000000
[  151.679331] RDX: 0000000000000001 RSI: 000000000002ee3b RDI: 0000000000000000
[  151.679331] RBP: 0000000000005707 R08: 0000000000000001 R09: 0000000000000001
[  151.679331] R10: 0000000000000080 R11: 00000000ac3f204b R12: 0000000000000008
[  151.679331] R13: ffff88016d1e1d48 R14: 0000000000000001 R15: ffff88016d1e1d48
[  151.679331] FS:  00007f2d503df700(0000) GS:ffff88051fc80000(0000) knlGS:0000000000000000
[  151.679331] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  151.679331] CR2: 000000000040a2a6 CR3: 00000000d88db000 CR4: 00000000000006e0
[  151.679331] Stack:
[  151.679331]  ffff8801a90ebd78 ffffffff8109fb58 ffff8801e0e619e0 ffff8801a90ebd78
[  151.679331]  ffffffff8109fb58 ffffffff8125413b ffff8801a90ebd78 0000000000000001
[  151.679331]  ffff88016d1e1d48 ffffffff8109fb58 ffff880171e792c0 ffffffff8124e849
[  151.679331] Call Trace:
[  151.679331]  [<ffffffff8109fb58>] ? __lock_task_sighand+0xe8/0x140
[  151.679331]  [<ffffffff8109fb58>] ? __lock_task_sighand+0xe8/0x140
[  151.679331]  [<ffffffff8125413b>] ? kt_mtx_pre_unlock+0x4b/0xc0
[  151.679331]  [<ffffffff8109fb58>] ? __lock_task_sighand+0xe8/0x140
[  151.679331]  [<ffffffff8124e849>] ? ktsan_mtx_pre_unlock+0xb9/0xc0
[  151.679331]  [<ffffffff8109fb58>] ? __lock_task_sighand+0xe8/0x140
[  151.679331]  [<ffffffff81311e36>] ? do_task_stat+0x116/0xda0
[  151.679331]  [<ffffffff81550ed3>] ? memcmp+0x83/0xa0
[  151.679331]  [<ffffffff8125132e>] ? kt_spin_unlock+0xe/0x20
[  151.679331]  [<ffffffff8125132e>] ? kt_spin_unlock+0xe/0x20
[  151.679331]  [<ffffffff81254d0b>] ? kt_tab_access+0x11b/0x1b0
[  151.679331]  [<ffffffff81254ae3>] ? kt_sync_release+0x93/0x160
[  151.679331]  [<ffffffff813138f7>] ? proc_tgid_stat+0x37/0x50
[  151.679331]  [<ffffffff8130ccab>] ? proc_single_show+0x8b/0xd0
[  151.679331]  [<ffffffff8129947e>] ? seq_read+0x16e/0x760
[  151.679331]  [<ffffffff8125c93f>] ? __vfs_read+0x5f/0x1e0
[  151.679331]  [<ffffffff814999cf>] ? security_file_permission+0x6f/0x120
[  151.679331]  [<ffffffff8125d6c1>] ? rw_verify_area+0xa1/0x180
[  151.679331]  [<ffffffff8125d857>] ? vfs_read+0xb7/0x1e0
[  151.679331]  [<ffffffff8125edb0>] ? SyS_read+0x70/0xd0
[  162.392886]  [<ffffffff81ed753a>] ? entry_SYSCALL_64_fastpath+0x1a/0x95
[  162.392886]  [<ffffffff81ed7551>] ? entry_SYSCALL_64_fastpath+0x31/0x95
[  162.392886] Code: 83 c4 10 5b 5d 41 5c c3 89 54 24 0c 48 89 34 24 e8 83 80 00 00 8b 54 24 0c 48 8b 34 24 e9 24 ff ff ff 0f 0b 0f 0b 4c 89 c9 eb 9c <0f> 0b 90 90 90 90 90 90 90 90 90 90 90 44 8b 87 c8 80 08 00 45 
[  162.400899] RIP  [<ffffffff81250ab3>] kt_mutex_unlock+0x113/0x120
[  162.400899]  RSP <ffff88016cbffa88>
[  162.400899] ---[ end trace 0c12083548476300 ]---
```

### PR DESCRIPTION
**Pull request by xairy**
Fixes #105

### CODE REVIEW

File: mm/ktsan/mutexset.c [hunk 1]
```diff
@@ -29,7 +29,9 @@ void kt_mutexset_unlock(kt_mutexset_t *set, u64 uid, bool wr)
 			return;
 		}
 	}
-	BUG();
+
+	/* We could BUG() here, but instead in kt_mtx_pre_unlock we print
+	   a report saying that mutex was unlocked in another thread.*/
```
Comment (dvyukov) [inline mm/ktsan/mutexset.c]: add a space before */

**Comment by dvyukov** [comment]
LGTM

File: mm/ktsan/mutexset.c (hunk 1 above)
Comment (xairy) [inline mm/ktsan/mutexset.c]: Done.
