### PR TITLE
Fix detecting racy-use-after-frees && fix false positives due to SLAB_DESTROY_BY_RCU

### LINKED ISSUE #88: False positives due to SLAB_DESTROY_BY_RCU
This is false positives. Free into SLAB_DESTROY_BY_RCU slab must not write to object.

```
ThreadSanitizer: data-race in kmem_cache_free

Write at 0xffff8804852e1588 of size 8 by thread 2962 on CPU 8:
 [<     inline     >] __cache_free mm/slab.c:3384
 [<ffffffff812451f2>] kmem_cache_free+0x92/0x480 mm/slab.c:3562
 [<ffffffff81086d0b>] __cleanup_sighand+0x5b/0x70 kernel/fork.c:1096
 [<     inline     >] __exit_signal kernel/exit.c:151
 [<ffffffff8108cf25>] release_task+0x855/0xaa0 kernel/exit.c:184
 [<     inline     >] wait_task_zombie kernel/exit.c:1111
 [<ffffffff8108ef41>] wait_consider_task+0x9f1/0x18a0 kernel/exit.c:1354
 [<     inline     >] do_wait_thread kernel/exit.c:1417
 [<ffffffff8108ff9f>] do_wait+0x1af/0x3b0 kernel/exit.c:1488
 [<     inline     >] SYSC_wait4 kernel/exit.c:1615
 [<ffffffff810906d5>] SyS_wait4+0xe5/0x160 kernel/exit.c:1584
 [<ffffffff81ee3e11>] entry_SYSCALL_64_fastpath+0x31/0x95 arch/x86/entry/entry_64.S:188

Previous read at 0xffff8804852e1588 of size 1 by thread 2961 on CPU 5:
 [<     inline     >] __raw_spin_unlock include/linux/spinlock_api_smp.h:165
 [<     inline     >] spin_unlock include/linux/spinlock.h:357
 [<ffffffff8109fe28>] __lock_task_sighand+0xe8/0x140 kernel/signal.c:1289
 [<     inline     >] lock_task_sighand include/linux/sched.h:2720
 [<ffffffff8109feb0>] do_send_sig_info+0x30/0xa0 kernel/signal.c:1186
 [<ffffffff810a0595>] group_send_sig_info+0x55/0x70 kernel/signal.c:1309
 [<ffffffff810a0743>] kill_pid_info+0x43/0x90 kernel/signal.c:1343
 [<     inline     >] kill_something_info kernel/signal.c:1426
 [<ffffffff810a0903>] SYSC_kill+0x123/0x2f0 kernel/signal.c:2906
 [<ffffffff810a3520>] SyS_kill+0x20/0x30 kernel/signal.c:2896
 [<ffffffff81ee3e11>] entry_SYSCALL_64_fastpath+0x31/0x95 arch/x86/entry/entry_64.S:188

Mutexes locked by thread 2962:
Mutex 195 is locked here:
 [<     inline     >] __raw_write_lock_irq include/linux/rwlock_api_smp.h:217
 [<ffffffff81ee38d4>] _raw_write_lock_irq+0x64/0x70 kernel/locking/spinlock.c:311
 [<ffffffff8108c745>] release_task+0x75/0xaa0 kernel/exit.c:182
 [<     inline     >] wait_task_zombie kernel/exit.c:1111
 [<ffffffff8108ef41>] wait_consider_task+0x9f1/0x18a0 kernel/exit.c:1354
 [<     inline     >] do_wait_thread kernel/exit.c:1417
 [<ffffffff8108ff9f>] do_wait+0x1af/0x3b0 kernel/exit.c:1488
 [<     inline     >] SYSC_wait4 kernel/exit.c:1615
 [<ffffffff810906d5>] SyS_wait4+0xe5/0x160 kernel/exit.c:1584
 [<ffffffff81ee3e11>] entry_SYSCALL_64_fastpath+0x31/0x95 arch/x86/entry/entry_64.S:188

Mutexes locked by thread 2961:
Mutex 517812 is locked here:
 [<     inline     >] __raw_spin_lock include/linux/spinlock_api_smp.h:158
 [<ffffffff81ee37d0>] _raw_spin_lock+0x50/0x70 kernel/locking/spinlock.c:151
 [<     inline     >] spin_lock include/linux/spinlock.h:312
 [<ffffffff8109fdad>] __lock_task_sighand+0x6d/0x140 kernel/signal.c:1284
 [<     inline     >] lock_task_sighand include/linux/sched.h:2720
 [<ffffffff8109feb0>] do_send_sig_info+0x30/0xa0 kernel/signal.c:1186
 [<ffffffff810a0595>] group_send_sig_info+0x55/0x70 kernel/signal.c:1309
[<ffffffff810a0743>] kill_pid_info+0x43/0x90
 [<     inline     >] kill_something_info kernel/signal.c:1426
 [<ffffffff810a0903>] SYSC_kill+0x123/0x2f0 kernel/signal.c:2906
 [<ffffffff810a3520>] SyS_kill+0x20/0x30 kernel/signal.c:2896
 [<ffffffff81ee3e11>] entry_SYSCALL_64_fastpath+0x31/0x95 arch/x86/entry/entry_64.S:188
```

### PR DESCRIPTION
**Pull request by xairy**
Fixes #88

### CODE REVIEW

File: mm/ktsan/shadow.c [hunk 1]
```diff
@@ -68,6 +57,18 @@ void ktsan_free_page(struct page *page, unsigned int order)
 	kt_atomic64_fetch_add_no_ktsan(&kt_shadow_pages,
 		-(1 << (order + KT_SHADOW_SLOTS_LOG)));
 
+	page_addr = (unsigned long)page_address(page);
```
Comment (dvyukov) [inline mm/ktsan/shadow.c]: I don't understand this. When we add sync objects to memblocks, we don't check that shadow is mapped. So we leak sync objects in pages without shadow or what?

File: mm/ktsan/tests_inst.c [hunk 2]
```diff
@@ -155,8 +158,116 @@ static void stack_race_write(void *arg)
...
+
+	kmem_cache_destroy(arg->cache);
+}
+
+static void sdbr_obj_free(void *p)
+{
+	struct sdbr_arg *arg = (struct sdbr_arg *)p;
+	struct sdbr_obj *obj;
+
+	obj = rcu_dereference(arg->obj);
```
Comment (dvyukov) [inline mm/ktsan/tests_inst.c]: rcu_dereference/rcu_assign_pointer are for objects published during concurrent read-only traversal. I don't understand why you use it here. arg->obj is not concurrently published, it is created before this thread is started. READ_ONCE/WRITE_ONCE is enough here.

File: mm/ktsan/tests_inst.c [hunk 3]
```diff
@@ -155,8 +158,116 @@ static void stack_race_write(void *arg)
...
+	rcu_assign_pointer(arg->obj, NULL);
```
Comment (dvyukov) [inline mm/ktsan/tests_inst.c]: Write a more realistic example: reallocate the object and install it again into arg->obj. I suspect you will discover a bug on such test.

File: mm/slab.c [hunk 4]
```diff
@@ -3381,7 +3381,8 @@ static inline void __cache_free(struct kmem_cache *cachep, void *objp,
 	kmemleak_free_recursive(objp, cachep->flags);
 	objp = cache_free_debugcheck(cachep, objp, caller);
 
-	ktsan_memblock_free(objp, cachep->object_size);
+	ktsan_memblock_free(objp, cachep->object_size,
+			!(cachep->flags & SLAB_DESTROY_BY_RCU));
```
Comment (dvyukov) [inline mm/slab.c]: I don't like that we have this logic in mm/slab.c (not our file). We will need to touch mm/ files when we want to change the condition. Let's do a more robust thing -- pass in cachep object and look at flags inside.

File: mm/ktsan/tests_inst.c (hunk 3 above)
Comment (xairy) [inline mm/ktsan/tests_inst.c]: Yes, I did.
What's is a better way to fix this?
Imitate a read (instead of a write) access on memblock allocation?
Or just clear shadow for SLAB_DESTROY_BY_RCU slabs on memblock allocation?

File: mm/slab.c (hunk 4 above)
Comment (xairy) [inline mm/slab.c]: Passed flags as an argument.

File: mm/ktsan/tests_inst.c (hunk 2 above)
Comment (xairy) [inline mm/ktsan/tests_inst.c]: Done.

File: mm/ktsan/shadow.c (hunk 1 above)
Comment (xairy) [inline mm/ktsan/shadow.c]: You are right, it should be fixed in a different way.
Now we always free syncs if memblock exists and always do write to shadow if it is mapped.

File: mm/ktsan/tests_inst.c (hunk 3 above)
Comment (dvyukov) [inline mm/ktsan/tests_inst.c]: Read still can lead to false positives if the thread that uses the object after free writes to the object (which threads actually do, e.g. when locking a spinlock in the object).
Do nothing.
All such slabs should have a ctor, we should clear the shadow before calling the ctor (do we?).

File: mm/ktsan/tests_inst.c [hunk 5]
```diff
@@ -155,8 +158,134 @@ static void stack_race_write(void *arg)
...
+		kmem_cache_free(arg->cache, arg->obj);
+	kmem_cache_destroy(arg->cache);
+}
+
+static void sdbr_obj_free(void *p)
+{
+	struct sdbr_arg *arg = (struct sdbr_arg *)p;
+	struct sdbr_obj *obj;
+
+	obj = READ_ONCE(arg->obj);
```
Comment (dvyukov) [inline mm/ktsan/tests_inst.c]: s/READ_ONCE// there are no concurrent writes to the variable

File: mm/ktsan/tests_inst.c [hunk 6]
```diff
@@ -155,8 +158,134 @@ static void stack_race_write(void *arg)
...
+}
+
+static void sdbr_obj_use(void *p)
+{
+	struct sdbr_arg *arg = (struct sdbr_arg *)p;
+	struct sdbr_obj *obj;
+	int i;
+
+	rcu_read_lock();
+	obj = rcu_dereference(arg->obj);
```
Comment (dvyukov) [inline mm/ktsan/tests_inst.c]: s/rcu_dereference/READ_ONCE/ there are no new objects published concurrently

Comment (xairy) [inline mm/ktsan/tests_inst.c]: There are. In sdbr_obj_realloc vs sdbr_obj_use test.

Comment (dvyukov) [inline mm/ktsan/tests_inst.c]: You are right. Sorry.

**Comment by dvyukov** [comment]
LGTM

File: mm/ktsan/tests_inst.c (hunk 3 above)
Comment (xairy) [inline mm/ktsan/tests_inst.c]: Do nothing: done.

> All such slabs should have a ctor, we should clear the shadow before calling the ctor (do we?).
But if we're inside a rcu read critical section, and we got a reference to an object, which is being concurrently freed, we can still access the object after ctor is called in another thread, as I understand.

File: mm/ktsan/tests_inst.c (hunk 5 above)
Comment (xairy) [inline mm/ktsan/tests_inst.c]: Done.
